import sys
import os
import uuid
from log_parser import LogParser
from llm_client import LLMClient
from git_ops import GitOps

def main():
    print("Starting AI Healer Agent...")
    
    # 1. Read the log file passed as argument
    if len(sys.argv) < 2:
        print("Usage: python agent.py <path_to_log_file>")
        sys.exit(1)
        
    log_file_path = sys.argv[1]
    with open(log_file_path, 'r') as f:
        log_content = f.read()
        
    # 2. Parse the log to find the error
    parser = LogParser()
    error_info = parser.parse_failure(log_content)
    
    if not error_info:
        print("No parseable error found in logs. Exiting.")
        sys.exit(0)
        
    print(f"Found error in {error_info['file_path']}: {error_info['error_message']}")
    
    # 3. Read the failing file
    try:
        with open(error_info['file_path'], 'r') as f:
            file_content = f.read()
    except FileNotFoundError:
        print(f"File {error_info['file_path']} not found.")
        sys.exit(1)
        
    # 4. Get Fix from LLM
    llm = LLMClient()
    fixed_content = llm.get_fix(file_content, error_info)
    
    # 5. Apply Fix and Create PR
    branch_name = f"fix/ai-heal-{uuid.uuid4().hex[:8]}"
    git_ops = GitOps()
    
    git_ops.create_branch(branch_name)
    
    with open(error_info['file_path'], 'w') as f:
        f.write(fixed_content)
        
    git_ops.commit_changes(error_info['file_path'], f"fix: AI repair for {error_info['error_message']}")
    git_ops.push_changes(branch_name)
    
    git_ops.create_pr(
        branch_name, 
        f"AI Fix: {error_info['error_message']}", 
        f"Automated fix generated by AI Healer Agent.\n\nError: `{error_info['error_message']}`"
    )

if __name__ == "__main__":
    main()
